// SPDX-FileCopyrightText: 2026 Space Station 14 Contributors
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Utility;
using System.IO;
using System.Numerics;

namespace Content.Client._Pirate.Photo.UI;

[GenerateTypedNameReferences]
public sealed partial class PhotoCardWindow : BaseWindow
{
    private const int DRAG_MARGIN_SIZE = 16;

    private DragMode _allowedResizeModes = DragMode.None;

    public PhotoCardWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        var resourceCache = IoCManager.Resolve<IResourceCache>();
        PhotoNameLabel.FontOverride = resourceCache.NotoStack(variation: "Bold", size: 12);
        CaptionLabel.ModulateSelfOverride = Color.FromHex("#111111");

        CloseButton.OnPressed += _ => Close();
    }

    public void ShowImage(byte[] imageData)
    {
        try
        {
            using var stream = new MemoryStream(imageData);
            ImageDisplay.Texture = Texture.LoadFromPNGStream(stream);
        }
        catch
        {
            ImageDisplay.Texture = null;
        }
    }

    public void SetMetadata(string? customName, string? caption)
    {
        PhotoNameLabel.Text = customName ?? string.Empty;
        CaptionLabel.SetMessage(FormattedMessage.FromUnformatted(caption ?? string.Empty));
    }

    protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
    {
        var mode = DragMode.None;

        // Be quite generous with resize margins:
        if (relativeMousePos.Y < DRAG_MARGIN_SIZE)
        {
            mode |= DragMode.Top;
        }
        else if (relativeMousePos.Y > Size.Y - DRAG_MARGIN_SIZE)
        {
            mode |= DragMode.Bottom;
        }

        if (relativeMousePos.X < DRAG_MARGIN_SIZE)
        {
            mode |= DragMode.Left;
        }
        else if (relativeMousePos.X > Size.X - DRAG_MARGIN_SIZE)
        {
            mode |= DragMode.Right;
        }

        if ((mode & _allowedResizeModes) == DragMode.None)
        {
            return DragMode.Move;
        }
        return mode & _allowedResizeModes;
    }
}
